### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by JiafengtTang** [ShimonMalnick/taming_norm_flows#1]
Hi, your work is food. When release this code?

**Comment by ShimonMalnick** [comment]
Hi, thanks a lot for your interest in our work!
Unfortunately, due to the current war in Israel and the fact that I have
been drafted, the release date remains undetermined. We will release it as
soon as circumstances permit.

**Comment by JiafengtTang** [comment]
感谢您的回复。在这充满挑战的时刻，我真诚地希望您的安全和健康。

**Comment by JiafengtTang** [comment]
Thank you for your response. I sincerely hope for your safety and well-being during these challenging times.

**Comment by ShimonMalnick** [comment]
Thank you very much for your concern! the code has finally been released 👏
